repos:
  - repo: local
    hooks:
      - id: build
        name: Build Typst PDF & HTML
        entry: python3 scripts/build.py
        language: python
        pass_filenames: false
        additional_dependencies:
          - pyyaml
